name: command_in_github_virtual_env
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      os:
        description: OS
        required: false
        default: ubuntu-latest
      cmd:
        description: command
        required: true

jobs:
  command_in_github_virtual_env:
    runs-on: ${{ github.event.inputs.os || 'ubuntu-latest' }}
    steps:
      - run: ${{ github.event.inputs.cmd || 'echo' }}
