name: deploy
on:
  workflow_dispatch:
    inputs:
      target:
        description: deploy target
        type: choice
        default: staging
        required: true
        options:
          - staging
          - production
      cipher:
        description: cipher
        type: choice
        default: ed25519
        required: true
        options:
          - ed25519
          - rsa
          - ecdsa
          - dsa
      debug:
        description: debug mode
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      # GITHUB ENVIROMENT is appropriate to use, but it is not available for private repository
      - name: deploy to staging
        if: ${{ inputs.target == 'staging' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_STAGING_SSH_HOST }}
          port: ${{ vars.DEPLOY_STAGING_SSH_PORT }}
          fingerprint: ${{ vars.DEPLOY_STAGING_SSH_HOST_FINGERPRINT }}
          username: ${{ vars.DEPLOY_STAGING_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DEPLOY_STAGING_SSH_PRIVATE_KEY_PASSPHRASE }}
          script: ${{ vars.DEPLOY_STAGING_SSH_CMD }}
          debug: ${{ inputs.debug }}
          cipher: ${{ inputs.cipher }}

      - name: deploy to production
        if: ${{ inputs.target == 'production' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_PRODUCTION_SSH_HOST }}
          port: ${{ vars.DEPLOY_PRODUCTION_SSH_PORT }}
          fingerprint: ${{ vars.DEPLOY_PRODUCTION_SSH_HOST_FINGERPRINT }}
          username: ${{ vars.DEPLOY_PRODUCTION_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_PRODUCTION_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DEPLOY_PRODUCTION_SSH_PRIVATE_KEY_PASSPHRASE }}
          script: ${{ vars.DEPLOY_PRODUCTION_SSH_CMD }}
          debug: ${{ inputs.debug }}
          cipher: ${{ inputs.cipher }}
